# Generated by Django 3.2.7 on 2021-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20211107_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(max_length=8, null=True),
        ),
    ]
